version: "3.8"

services:
  app:
    build: .
    container_name: fastapi_app
    environment:
      - API_ENV=${API_ENV}  # 환경 변수 설정
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db # 명명 볼륨 사용
  redis:
      image: redis:latest  # Redis 이미지
      container_name: redis
      ports:
        - "6379:6379"  # Redis 기본 포트

volumes:
  mongo_data: # mongodb 서비스의 명명 볼륨
