version: "3.8"

services:
  app:
    build: .
    container_name: fastapi_app
    environment:
      - API_ENV=${API_ENV}  # 환경 변수 설정
      - PYTHONPATH=/app
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./app:/app/app  # 호스트의 app 폴더를 컨테이너의 /app에 연결
      - ./uploads:/app/uploads  # 호스트의 uploads 폴더를 컨테이너의 /app/uploads에 연결
    # 경로 확인 후 uvicorn 실행
    # sh -c 'ls /app/app && echo "Current directory: $(pwd)" && uvicorn main:app --host 0.0.0.0 --port 8000'
    command: >
      sh -c 'echo "Checking files in /app:" && ls -la /app && echo "Checking files in /app/app:" && ls -la /app/app && uvicorn main:app --host 0.0.0.0 --port 8000'

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db # 명명 볼륨 사용
  redis:
      image: redis:latest  # Redis 이미지
      container_name: redis
      ports:
        - "6379:6379"  # Redis 기본 포트

volumes:
  mongo_data: # mongodb 서비스의 명명 볼륨
